# Adapted from:
# https://www.blackbaud.com/support/howto/coveo/luminate-online/subsystems/donation_management/content/concepts/Admin_DonationManagement_AutomaticConstituentFormattingValidation_Name.html
class NameCleaner
  def initialize(first_name, last_name)
    @first_name = first_name
    @last_name = last_name
  end

  def clean_first_name
    mixed_case(@first_name) ? @first_name : @first_name.titleize
  end

  def clean_last_name
    return @last_name if mixed_case(@last_name)

    special = surnames.map(&:downcase).index(@last_name.downcase)
    return surnames[special] unless special.nil?

    @last_name = @last_name.titleize
    @last_name = scotch(@last_name)
    @last_name = downcase_articles(@last_name)
    @last_name = post_apostrophe(@last_name)
    @last_name
  end

  private

  def surnames
    %w[
      D'Amico
      DaCosta
      DaSilva
      DaVeiga
      DeAngelis
      DeAngelo
      DeBartolo
      DeBell
      DeBenedictis
      DeBerry
      DeBlasio
      DeBoer
      DeBonis
      DeBord
      DeBruin
      DeCamp
      DeCarlo
      DeCaro
      DeChant
      DeChirico
      DeCicco
      DeClue
      DeCosta
      DeCuir
      DeFalco
      DeFazio
      DeFelice
      DeFeo
      DeFilippis
      DeFilippo
      DeFoe
      DeFord
      DeForest
      DeFrancesco
      DeFranco
      DeGarmo
      DeGennaro
      DeGolyer
      DeGraff
      DeGraw
      DeGregorio
      DeGroat
      DeGroot
      DeHaan
      DeHart
      DeHaven
      DeJesus
      DeJohn
      DeJong
      DeLacy
      DeLancey
      DeLapp
      DeLaura
      DeLaurentis
      DeLay
      DeLeo
      DeLeon
      DeLisle
      DeLoach
      DeLong
      DeLorenzo
      DeLorey
      DeLozier
      DeLuca
      DeLucia
      DeMaio
      DeMarco
      DeMaria
      DeMars
      DeMartini
      DeMartino
      DeMasi
      DeMatteo
      DeMay
      DeMello
      DeMeo
      DeMeritt
      DeMichele
      DeMille
      DeMoss
      DeMott
      DeMuth
      DeNicola
      DePalma
      DePaolo
      DePasquale
      DePaula
      DePew
      DePhillips
      DePriest
      DePuy
      DeRosa
      DeRose
      DeRosier
      DeRouen
      DeSalvo
      DeSantis
      DeSanto
      DeSena
      DeShazo
      DeSilva
      DeSimone
      DeSoto
      DeSouza
      DeSpain
      DeStefano
      DeVaughn
      DeVault
      DeVere
      DeVille
      DeVincenzo
      DeVita
      DeVito
      DeVoe
      DeVore
      DeVos
      DeVries
      DeWald
      DeWalt
      DeWees
      DeWeese
      DeWitt
      DeWolf
      DeYoung
      DelGiudice
      DelGreco
      DelVecchio
      DellaLoggia
      DesJardins
      DesLauriers
      DiBello
      DiBenedetto
      DiBernardo
      DiBiase
      DiBona
      DiCamillo
      DiCarlo
      DiCicc
      DiCostanzo
      DiDomenico
      DiFazio
      DiFiore
      DiFrancesco
      DiGiacomo
      DiGioia
      DiGiorgio
      DiGiovanni
      DiGrazia
      DiJulio
      DiLallo
      DiLeo
      DiLorenzo
      DiLoreto
      DiMaggio
      DiMambro
      DiMarco
      DiMaria
      DiMartino
      DiMatteo
      DiMattia
      DiMauro
      DiMeglio
      DiNardo
      DiNatale
      DiPalma
      DiPaola
      DiPaolo
      DiPasquale
      DiPierro
      DiPietro
      DiRocco
      DiSalvo
      DiSanto
      DiStefano
      DiTullio
      DiVito
      DuBois
      DuBose
      DuFresne
      DuPre
      FitzGerald
      LaBarbera
      LaBarge
      LaBarre
      LaBella
      LaBelle
      LaBianca
      LaBonte
      LaBounty
      LaBranche
      LaBrecque
      LaBrie
      LaCasse
      LaChance
      LaChapelle
      LaClair
      LaCour
      LaCroix
      LaCrosse
      LaDue
      LaFave
      LaFever
      LaFlamme
      LaFleur
      LaFollette
      LaFon
      LaFontaine
      LaForce
      LaForest
      LaForge
      LaFrance
      LaFreniere
      LaGorga
      LaGrone
      LaGuardia
      LaLiberte
      LaLonde
      LaManna
      LaMantia
      LaMarca
      LaMarche
      LaMonica
      LaMontagne
      LaMothe
      LaMotte
      LaPlaca
      LaPlant
      LaPlante
      LaPoint
      LaPointe
      LaPorta
      LaPorte
      LaPrade
      LaReau
      LaRocca
      LaRocco
      LaRoche
      LaRochelle
      LaRock
      LaRocque
      LaRoe
      LaRosa
      LaRose
      LaRue
      LaSalle
      LaTorre
      LaTour
      LaValle
      LaValley
      LaVerne
      LeAnn
      LeBaron
      LeBeau
      LeBlanc
      LeBoeuf
      LeBrun
      LeClair
      LeClaire
      LeCompte
      LeCroy
      LeDoux
      LeDrew
      LeDuc
      LeFevre
      LeGrand
      LeJeune
      LeMaire
      LeMaster
      LeMasters
      LeMay
      LePage
      LeRoux
      LeRoy
      LeSage
      LeTourneau
      LeVan
      LeVasseur
      LeeAnn
      LoCicero
      LoGerfo
      LoPreste
      LoPresti
      LuAnn
      Mac
      Macaluso
      Macartney
      Macaulay
      Macauley
      Maccarone
      Macchia
      Mace
      Maceda
      Macedo
      Macek
      Macey
      Mach
      Machacek
      Machado
      Machen
      Machin
      Macias
      Maciejewski
      Mack
      Mackay
      Macke
      Mackel
      Mackey
      Mackie
      Mackin
      Macklin
      Macko
      Macky
      Macomber
      Macon
      Macri
      Macy
      O'Brien
      O'Connell
      O'Connor
      O'Dell
      O'Donnell
      O'Grady
      O'Hara
      O'Keefe
      O'Leary
      O'Leyar
      O'Loughlin
      O'Malley
      O'Neal
      O'Neil
      O'Neill
      O'Rourke
      O'Sullivan
      StClair
      StJohn
      VanBuren
      VanBuskirk
      VanDyke
      VanEtten
      VanHorn
      VanHouten
      VanLandingham
      VanPelt
      VanSickle
      VanWormer
      deAndrade
      deForest
    ]
  end

  def mixed_case(str)
    !(/[A-Z]/ =~ str).nil? && !(/[a-z]/ =~ str).nil? && (/\s/ =~ str).nil? &&
      (/\w'\w/ =~ str).nil?
  end

  def scotch(str)
    str.gsub(/^(Ma?c)([a-z])(\w+)/) { |match| "#{$1}#{$2.upcase}#{$3}" }
  end

  def post_apostrophe(str)
    str.gsub(/^(\w{1}')(\w)(\w+)/) { |match| "#{$1}#{$2.upcase}#{$3}" }
  end

  def downcase_articles(str)
    str.gsub(
      /(ab|ad|al|ap|as|d'|da|de|den|der|dos|ibn|la|n|ten|ul|und|van|von|y|zu)/i
    ) { |match| $&.downcase }
  end

  # extend self
end
